language: cpp python

python: '2.7'

compiler:  
  - gcc

before_script:  
  - files=`find . -path ./3rdparty -prune -name \*.hpp -print -o -name \*.h -print -o -name \*.cpp -print -o -name \*.c -print | sed -e ':a;N;$!ba;s/\n/ /g'`
  - python ./3rdparty/utils/cpplint.py --filter=-legal/copyright,-runtime/threadsafe_fn,-build/include,-readability/utf8 $files

script:   
  - mkdir build
  - cd build
  - cmake ..
  - make  

after_success:
   - find . -executable -type f -print | while read app; do "$app"; done